### PR TITLE
Added .dxf files of balenaFin v1.1

### PR DESCRIPTION
**Pull request by MTolba**
Change-type: patch
Signed-off-by: Mahmoud Tolba <mahmoud@balena.io>

### CODE REVIEW

**Review by curcuz — CHANGES_REQUESTED** [review]
the new path for the 3d Files need to be also updated [here](https://github.com/balena-io/balena-fin/blob/master/documentation/DOCUMENTATION.md#cad-files) and the new 2D ones need to be added too

**Comment by MTolba** [comment]
@curcuz I already added them [here](https://github.com/balena-io/balena-fin/blob/Add-.dxf-files-build-8cd1ef573d43e2fd51394ba4e9302e2ede32caa2/documentation/DOCUMENTATION.md)

**Comment by curcuz** [comment]
@MTolba sorry, for some reason it was not visible in the diff - had to reload :/

**Review by curcuz — APPROVED** [review]

**Comment by MTolba** [comment]
no worries buddy!

**Pull request merged**
