### PR TITLE
patch: Add balenaFin documentation

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Moving balenaFin docs from balena-site

TODO:
- Add versioning to the docusaurus template

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
These are ready to merge https://85916bbf.balena-fin.pages.dev/
@Bucknalla @hraftery Give them a look ✨ 

Any major improvements or structure changes can happen in future PRs

**Comment by Bucknalla** [comment]
@vipulgupta2048 I'm a bit confused about why we're mixing what was on the marketing website and this technical docs repository; this feels like conflating two different projects. I'm not sure they should exist in the same place; @hraftery what are your thoughts?

**Comment by vipulgupta2048** [comment]
@Bucknalla Sure, here's the improvement for context: https://jel.ly.fish/improvement-automatic-docs-sites-docusaurus--a55a30b 
Same as the etcherPro repo, this is the repo that was called balenaFin when I first started working on this PR. The landscape has changed since then. As product owner, please tell where this information should be best stored and I will make the PR there. 

This docs website will be redirected and made publically available on this URL: https://balena.io/fin/docs

**Comment by hraftery** [comment]
There's some overlap here, but being a public repo there's already some established expectation about what you find here. Let's leave this repo for the PDF/CAD/driver stuff and find a better home. The `fin` repos don't yet include a userManual repo and now's a great time to fix that and bring it inline with the `etcherPro` repos.

If you agree, please move this PR to the brand new https://github.com/balena-io-hardware/fin-userManual-doc

**Comment by vipulgupta2048** [comment]
Superseded by https://github.com/balena-io-hardware/fin-userManual-doc/pull/3

**Pull request closed without merging**
